services:
  api:
    build: .
    container_name: ceph-s3-api
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "8000:8000"
    volumes:
      - .:/app

  frontend:
    build: ./frontend
    container_name: ceph-s3-frontend
    restart: unless-stopped
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - api
